#Y contains the values connected from the anadata  

Y = {(the data in the anadata)}; 

my_y_sz = size(Y); 

value = Y(1,1); 

value = Y(2,1); 

dnl = zeros(my_y_sz); 

inl = zeros(my_y_sz); 

yideal = zeros(my_y_sz); 

ylsb = 1/63; 

ylsb; 

for i = 2:63 

    dnl(i,1) = Y(i,1) - Y((i-1),1) - ylsb; 

end 

DAC_input = zeros(my_y_sz); 

for i = 1:63 

    DAC_input(i,1)=i; 

end 

DAC_input; 

Plot_graph1(1) 

plot(DAC_input, dnl) 

 

for j = 1:63; 

    yideal(j,1) = j*ylsb; 

    inl(j,1)=Y(j,1)-yideal(j,1); 

end 

Plot_graph2(2) 

plot(DAC_input, inl) 
